image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - test
  - build

test:
  stage: test
  script:
    - python -mjson.tool 'pf1e_chn/cn.json' > /dev/null
    - python -mjson.tool 'pf1e_chn/module.json' > /dev/null

build:
  stage: build
  script:
    - zip pf1e_chn.zip -r pf1e_chn -x ".*"
  artifacts:
    name: pf1e_chn
    when: on_success
    paths:
      - pf1e_chn.zip
  when: on_success
  only:
    - tags
    - master
